'use client';
import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileText, Gavel, UploadCloud } from 'lucide-react';
import type { AnalysisResult, ClauseAnalysis } from '@/lib/types';
import { simpleDiff } from '@/lib/diff';
export default function Home(){const [file,setFile]=useState<File|null>(null);const [regulationName,setRegulationName]=useState('');const [loading,setLoading]=useState(false);const [result,setResult]=useState<AnalysisResult|null>(null);const [selected,setSelected]=useState<ClauseAnalysis|null>(null);async function submit(){const fd=new FormData();if(file)fd.append('file',file);fd.append('regulationName',regulationName);fd.append('purpose','실무검토용');setLoading(true);const res=await fetch('/api/analyze',{method:'POST',body:fd});const data=await res.json();setResult(data);setSelected(data.clauses[0]);setLoading(false)}const clauses=result?.clauses||[];return <main className="min-h-screen p-6 md:p-10"><section className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold text-blue-600">Regulation Diff Intelligence</p><h1 className="text-3xl md:text-4xl font-black tracking-tight">규정 신구조문 대비표 분석 대시보드</h1><p className="mt-2 text-gray-600">HWP/PDF 업로드 → 조문별 변경 분석 → 위험도·쟁점·실무 검토의견 생성</p></div><div className="rounded-2xl bg-slate-900 px-4 py-3 text-sm text-white">외부 접속 웹앱 MVP · MCP 연동 준비</div></header><div className="grid gap-6 lg:grid-cols-[380px_1fr]"><aside className="card p-5 space-y-4"><div className="flex items-center gap-2 font-bold"><UploadCloud size={20}/> 파일 업로드</div><label className="block"><span className="text-sm text-gray-600">규정명</span><input className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-2" value={regulationName} onChange={e=>setRegulationName(e.target.value)} placeholder="예: 학칙 시행세칙"/></label><label className="block rounded-2xl border-2 border-dashed border-gray-300 bg-gray-50 p-5 text-center cursor-pointer"><input type="file" accept=".hwp,.pdf" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/><FileText className="mx-auto mb-2"/><div className="font-bold">HWP/PDF 선택</div><div className="text-sm text-gray-500">{file?file.name:'파일을 선택하세요'}</div></label><button disabled={loading} onClick={submit} className="w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-50">{loading?'분석 중...':'분석 시작'}</button><div className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><b>보안 기본값</b><br/>외부 접속 웹앱 기준으로 로그인, 파일 비공개 저장, 원본 삭제 옵션을 전제로 설계.</div><McpCard/></aside><section className="space-y-6">{result?<><Summary result={result}/><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><ClauseList clauses={clauses} selected={selected} onSelect={setSelected}/>{selected&&<ClauseDetail clause={selected}/>}</div></>:<EmptyState/>}</section></div></section></main>}
function Summary({result}:{result:AnalysisResult}){const s=result.summary;return <div className="grid gap-3 md:grid-cols-5">{[['전체',s.total],['변경',s.changed],['신설',s.created],['삭제',s.deleted],['고위험',s.highRisk]].map(([k,v])=><div className="card p-4" key={k}><div className="text-sm text-gray-500">{k}</div><div className="text-3xl font-black">{v}</div></div>)}</div>}
function ClauseList({clauses,selected,onSelect}:{clauses:ClauseAnalysis[];selected:ClauseAnalysis|null;onSelect:(c:ClauseAnalysis)=>void}){return <div className="card overflow-hidden"><div className="border-b p-4 font-bold">조문 목록</div><div className="max-h-[720px] overflow-auto">{clauses.map(c=><button key={c.id} onClick={()=>onSelect(c)} className={`block w-full border-b p-4 text-left hover:bg-blue-50 ${selected?.id===c.id?'bg-blue-50':''}`}><div className="flex items-center justify-between gap-3"><b>{c.article}</b><span className={`badge ${riskClass(c.riskLevel)}`}>{c.riskLevel}</span></div><p className="mt-1 text-sm text-gray-600">{c.summary}</p><p className="mt-2 text-xs text-gray-500">{c.changeType} · 위험점수 {c.riskScore}</p></button>)}</div></div>}
function ClauseDetail({clause}:{clause:ClauseAnalysis}){const diff=useMemo(()=>simpleDiff(clause.oldText||'(없음)',clause.newText||'(없음)'),[clause]);return <div className="card p-5 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black">{clause.article}</h2><span className={`badge ${riskClass(clause.riskLevel)}`}>{clause.riskLevel} · {clause.riskScore}</span></div><div className="grid gap-4 md:grid-cols-2"><DiffBox title="구 조문" html={diff.oldHtml}/><DiffBox title="신 조문" html={diff.newHtml}/></div><Info title="개정 사유" text={clause.reason}/><Info title="변경 요약" text={clause.summary}/><Info title="실무 영향" text={clause.impact}/><div><h3 className="mb-2 font-bold flex items-center gap-2"><AlertTriangle size={18}/> 확인 질문</h3><ul className="list-disc pl-5 text-sm text-gray-700">{clause.questions.map(q=><li key={q}>{q}</li>)}</ul></div><Info title="검토 의견 초안" text={clause.opinionDraft}/><div className="rounded-2xl bg-slate-50 p-4"><h3 className="mb-2 font-bold flex items-center gap-2"><Gavel size={18}/> 법령/MCP 검토 키워드</h3><div className="flex flex-wrap gap-2">{clause.lawKeywords.map(k=><span className="badge bg-white border" key={k}>{k}</span>)}</div></div></div>}
function DiffBox({title,html}:{title:string;html:string}){return <div className="rounded-2xl border bg-white p-4"><h3 className="mb-2 font-bold">{title}</h3><p className="diff whitespace-pre-wrap text-sm leading-7" dangerouslySetInnerHTML={{__html:html}}/></div>}
function Info({title,text}:{title:string;text:string}){return <div><h3 className="mb-2 font-bold">{title}</h3><p className="rounded-2xl bg-gray-50 p-4 text-sm leading-7 text-gray-700">{text}</p></div>}
function McpCard(){return <div className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-950"><div className="mb-1 flex items-center gap-2 font-bold"><CheckCircle2 size={18}/> MCP 연동 예정</div><p>Korean Law MCP: 법령 검색/근거 확인<br/>Gordon MCP: 문서 추론/체크리스트 생성</p></div>}
function EmptyState(){return <div className="card p-10 text-center"><FileText className="mx-auto mb-3" size={42}/><h2 className="text-2xl font-black">분석할 대비표를 업로드하세요</h2><p className="mt-2 text-gray-600">현재 MVP는 화면·분석 흐름 검증용이며, 실제 HWP/PDF 파서는 다음 단계에서 샘플 파일 기준으로 정밀화합니다.</p></div>}
function riskClass(r:string){return r==='낮음'?'risk-low':r==='보통'?'risk-medium':r==='높음'?'risk-high':'risk-critical'}
