import { AnalysisResult, ClauseAnalysis, ChangeType, RiskLevel } from './types';
import type { ParsedComparisonRow, ParsedComparisonTable } from '@/lib/parsers/types';

const sampleRows=[{id:'sample-1',article:'제4조(위원회 구성)',oldText:'위원회는 위원장 1인을 포함하여 7인 이내의 위원으로 구성한다.',newText:'위원회는 위원장 1인을 포함하여 9인 이내의 위원으로 구성하며, 외부위원 1인 이상을 포함할 수 있다.',reason:'위원회 전문성 및 외부성 강화',confidence:1,warnings:[]},{id:'sample-2',article:'제8조(심의 절차)',oldText:'부서장은 필요한 경우 위원회 심의를 요청할 수 있다.',newText:'부서장은 개정안 시행 전 반드시 위원회 심의를 거쳐야 한다.',reason:'심의 절차 의무화',confidence:1,warnings:[]},{id:'sample-3',article:'제12조(자료 제출)',oldText:'',newText:'관련 부서는 위원회 요청 시 7일 이내에 검토자료를 제출하여야 한다.',reason:'자료 제출 근거 신설',confidence:1,warnings:[]},{id:'sample-4',article:'제15조(시행일)',oldText:'이 규정은 공포한 날부터 시행한다.',newText:'이 규정은 2026년 5월 1일부터 시행한다.',reason:'시행일 명확화',confidence:1,warnings:[]}];

export async function analyzeRegulation(input:{regulationName:string;purpose:string;sourceFormat:string;text?:string;parsedTable?:ParsedComparisonTable}):Promise<AnalysisResult>{
  const parsedRows=input.parsedTable?.rows;
  const rows=parsedRows?.length?parsedRows:sampleRows;
  const clauses=rows.map((row,i)=>classifyClause(row.id||String(i+1),row));
  const parserWarnings=input.parsedTable?.warnings;
  return {regulationName:input.parsedTable?.regulationName||input.regulationName||'업로드 규정',purpose:input.purpose||'실무검토용',sourceFormat:input.parsedTable?.sourceFormat||input.sourceFormat,previousHistory:input.parsedTable?.previousHistory,currentHistory:input.parsedTable?.currentHistory,parserWarnings,summary:{total:clauses.length,changed:clauses.filter(c=>c.oldText&&c.newText).length,created:clauses.filter(c=>!c.oldText&&c.newText).length,deleted:clauses.filter(c=>c.oldText&&!c.newText).length,highRisk:clauses.filter(c=>c.riskLevel==='높음'||c.riskLevel==='매우 높음').length,topFindings:clauses.slice().sort((a,b)=>b.riskScore-a.riskScore).slice(0,5).map(c=>`${c.article}: ${c.summary}`)},clauses};
}

function classifyClause(id:string,row:ParsedComparisonRow):ClauseAnalysis{const article=row.article||'조문 미상';const reason=row.reason||inferReason(row);const text=`${row.oldText} ${row.newText} ${reason}`;let changeType:ChangeType='문구 정비';let riskLevel:RiskLevel='낮음';let score=20;if(!row.oldText){changeType='신설';score=72;riskLevel='높음'}else if(!row.newText){changeType='삭제';score=78;riskLevel='높음'}else if(/반드시|하여야|의무|제출|승인|심의|거쳐야|허용|반환하지 아니한다/.test(text)){changeType='절차 변경';score=68;riskLevel='높음'}else if(/위원|부서장|총장|권한|책임|외부위원/.test(text)){changeType='권한\/책임 변경';score=55;riskLevel='보통'}else if(/기준|요건|자격|평가/.test(text)){changeType='기준\/요건 변경';score=70;riskLevel='높음'}const lawKeywords=[...text.matchAll(/고등교육법|사립학교법|교원자격검정령|대학설립·운영 규정|위원회|심의|자료 제출|등록금|휴학|자퇴/g)].map(m=>m[0]);return {id,article,oldText:row.oldText,newText:row.newText,reason,changeType,riskLevel,riskScore:score,summary:summarize(changeType),impact:impact(changeType),questions:questions(changeType),opinionDraft:opinion(changeType,{...row,reason}),lawKeywords:[...new Set(lawKeywords.length?lawKeywords:['관련 상위규정','위임 근거'])],parserConfidence:row.confidence,parserWarnings:row.warnings};}
function inferReason(row:ParsedComparisonRow){if(!row.oldText&&row.newText)return '신설';if(row.oldText&&!row.newText)return '삭제';return '공개 신구조문 대비표 기준 변경사항';}
function summarize(t:ChangeType){if(t==='신설')return '새로운 의무 또는 절차가 추가되었습니다.';if(t==='삭제')return '기존 근거 조항이 삭제되었습니다.';if(t==='절차 변경')return '임의 절차가 의무 절차로 강화되었을 가능성이 있습니다.';if(t==='권한/책임 변경')return '위원회 또는 담당 주체의 구성·책임 범위가 변경되었습니다.';return '표현 또는 운영 기준이 일부 정비되었습니다.'}
function impact(t:ChangeType){return t==='절차 변경'||t==='신설'?'실무 처리기간, 담당부서 업무량, 위원회 상정 필요성이 증가할 수 있습니다.':t==='권한/책임 변경'?'담당 주체와 의사결정 권한의 정합성 확인이 필요합니다.':'실무 영향은 제한적이나 다른 조항과 용어 일치 여부 확인이 필요합니다.'}
function questions(t:ChangeType){return ['상위 규정 또는 법령 위임 근거가 명확한가?','시행일 이전 경과조치가 필요한가?',t==='신설'||t==='절차 변경'?'담당부서가 실제 이행 가능한 절차인가?':'기존 조항과 용어가 일관되는가?'];}
function opinion(t:ChangeType,row:{reason:string}){return `본 개정안은 ${row.reason} 측면에서 필요성이 인정됩니다. 다만 ${t==='신설'||t==='절차 변경'?'의무 부과 및 절차 강화에 따른 상위 규정 근거와 실무 이행 가능성':'기존 규정 체계와의 정합성'}을 추가 확인한 후 확정하는 것이 타당합니다.`}
