import { AnalysisResult, ClauseAnalysis, ChangeType, HybridComparisonSummary, InputMode, RiskLevel, SourceMetadata } from './types';
import { buildDeterministicClauseReview } from './ai-review/fallback';
import { checkLegalCompliance, createConfiguredKoreanLawEvidenceRetriever, type LawEvidenceRetriever } from './mcp/korean-law-client';
import type { ParsedComparisonRow, ParsedComparisonTable } from '@/lib/parsers/types';

const sampleRows=[{id:'sample-1',article:'제4조(위원회 구성)',oldText:'위원회는 위원장 1인을 포함하여 7인 이내의 위원으로 구성한다.',newText:'위원회는 위원장 1인을 포함하여 9인 이내의 위원으로 구성하며, 외부위원 1인 이상을 포함할 수 있다.',reason:'위원회 전문성 및 외부성 강화',confidence:1,warnings:[]},{id:'sample-2',article:'제8조(심의 절차)',oldText:'부서장은 필요한 경우 위원회 심의를 요청할 수 있다.',newText:'부서장은 개정안 시행 전 반드시 위원회 심의를 거쳐야 한다.',reason:'심의 절차 의무화',confidence:1,warnings:[]},{id:'sample-3',article:'제12조(자료 제출)',oldText:'',newText:'관련 부서는 위원회 요청 시 7일 이내에 검토자료를 제출하여야 한다.',reason:'자료 제출 근거 신설',confidence:1,warnings:[]},{id:'sample-4',article:'제15조(시행일)',oldText:'이 규정은 공포한 날부터 시행한다.',newText:'이 규정은 2026년 5월 1일부터 시행한다.',reason:'시행일 명확화',confidence:1,warnings:[]}];

export async function analyzeRegulation(input:{regulationName:string;purpose:string;sourceFormat:string;text?:string;parsedTable?:ParsedComparisonTable;inputMode?:InputMode;sourceMetadata?:SourceMetadata[];hybridComparisonSummary?:HybridComparisonSummary;lawEvidenceRetriever?:LawEvidenceRetriever}):Promise<AnalysisResult>{
  const parsedRows=input.parsedTable?.rows;
  const rows=parsedRows?.length?parsedRows:sampleRows;
  const retriever=input.lawEvidenceRetriever||createConfiguredKoreanLawEvidenceRetriever();
  const baseClauses=rows.map((row,i)=>classifyClause(row.id||String(i+1),row));
  const clauses=await Promise.all(baseClauses.map(async clause=>({...clause,legalCheck:await checkLegalCompliance({clause,retriever})})));
  const parserWarnings=input.parsedTable?.warnings;
  return {regulationName:input.parsedTable?.regulationName||input.regulationName||'업로드 규정',purpose:input.purpose||'실무검토용',sourceFormat:input.parsedTable?.sourceFormat||input.sourceFormat,inputMode:input.inputMode,sourceMetadata:input.sourceMetadata,hybridComparisonSummary:input.hybridComparisonSummary,previousHistory:input.parsedTable?.previousHistory,currentHistory:input.parsedTable?.currentHistory,parserWarnings,summary:{total:clauses.length,changed:clauses.filter(c=>c.oldText&&c.newText).length,created:clauses.filter(c=>!c.oldText&&c.newText).length,deleted:clauses.filter(c=>c.oldText&&!c.newText).length,highRisk:clauses.filter(c=>c.riskLevel==='높음'||c.riskLevel==='매우 높음').length,topFindings:clauses.slice().sort((a,b)=>b.riskScore-a.riskScore).slice(0,5).map(c=>`${c.article}: ${c.summary}`)},clauses};
}

function classifyClause(id:string,row:ParsedComparisonRow):ClauseAnalysis{const article=row.article||'조문 미상';const reason=row.reason||inferReason(row);const text=`${article} ${row.oldText} ${row.newText} ${reason}`;const domain=buildDomainInsight(article,text,reason);let changeType:ChangeType='문구 정비';let riskLevel:RiskLevel='낮음';let score=20;if(domain){changeType=domain.changeType;score=domain.riskScore;riskLevel=domain.riskLevel}else if(!row.oldText){changeType='신설';score=72;riskLevel='높음'}else if(!row.newText){changeType='삭제';score=78;riskLevel='높음'}else if(reason==='변경'){changeType='변경';score=45;riskLevel='보통'}else if(/상\s*위\s*법\s*령|사립학교법|법령\s*개정/.test(text)){changeType='상위법령 반영 의심';score=76;riskLevel='높음'}else if(/반드시|하여야|의무|제출|승인|심의|거쳐야|허용|반환하지 아니한다/.test(text)){changeType='절차 변경';score=68;riskLevel='높음'}else if(/위원|부서장|총장|권한|책임|외부위원|외부\s*전문가/.test(text)){changeType='권한\/책임 변경';score=55;riskLevel='보통'}else if(/기준|요건|자격|평가|배점|점수|정원/.test(text)){changeType='기준\/요건 변경';score=70;riskLevel='높음'}const lawKeywords=[...text.matchAll(/고등교육법|사립학교법|교원자격검정령|대학설립·운영 규정|대학원 학칙 시행세칙|교원 인사 규정|위원회|심의|자료 제출|등록금|휴학|자퇴/g)].map(m=>m[0]);const uniqueLawKeywords=[...new Set(lawKeywords.length?lawKeywords:['관련 상위규정','위임 근거'])];const aiReview=buildDeterministicClauseReview({row:{...row,reason},changeType,riskScore:score,lawKeywords:uniqueLawKeywords});return {id,article,oldText:row.oldText,newText:row.newText,reason,changeType,riskLevel,riskScore:aiReview.risk.riskScore,summary:domain?.summary??summarize(changeType),impact:domain?.impact??aiReview.risk.practicalImpact,questions:domain?.questions??aiReview.risk.reviewQuestions,opinionDraft:domain?.opinionDraft??aiReview.risk.opinionDraft,lawKeywords:uniqueLawKeywords,legalEvidenceStatus:aiReview.legalEvidence.status,legalEvidenceReason:aiReview.legalEvidence.missingEvidenceReason,riskDrivers:domain?.riskDrivers??aiReview.risk.riskDrivers,aiReviewMode:aiReview.mode,aiReview,parserConfidence:row.confidence,parserWarnings:row.warnings};}
type DomainInsight={changeType:ChangeType;riskLevel:RiskLevel;riskScore:number;summary:string;impact:string;questions:string[];opinionDraft:string;riskDrivers:string[]};

function buildDomainInsight(article:string,text:string,reason:string):DomainInsight|undefined{
  const compact=text.replace(/\s+/g,'');
  if(/별표.*영역별평가항목및배점|석박사|공동지도교수|필수업적/.test(compact)&&/별표/.test(article))return {changeType:'기준/요건 변경',riskLevel:'높음',riskScore:80,summary:'별표의 교육·연구영역 배점표를 수정하고, 석·박사 배출 및 공동지도교수 배점 기준을 구체화하는 개정입니다.',impact:'평가 배점표, 공동지도교수 배점 배분, 대학원 학칙 시행세칙과의 연결이 실무 처리에 직접 영향을 줍니다. 별표 수치와 본문 조항의 참조관계 검산이 필요합니다.',questions:['공동지도교수 50:50 배분이 대학원 학칙 시행세칙 제31조와 정확히 연결되는가?','별표 수치가 기존 산식과 비교해 누락·중복 없이 이전되었는가?','비고의 항신설·항순연 내용이 실제 별표 번호 체계와 일치하는가?'],opinionDraft:'별표 개정은 실제 평가점수 산정에 직접 영향을 주므로, 수치 검산과 공동지도교수 배점 기준의 근거 조항 확인이 선행되어야 합니다. 특히 항신설·항순연으로 인한 참조 오류가 없는지 확인 후 확정하는 것이 타당합니다.',riskDrivers:['별표 배점표 직접 변경','공동지도교수 배점 배분 신설','수치·항번호 검산 필요']};
  if(/제4조\(영역별평가항목\)|필수업적\(간접비\)|연구영역.*논문등|연구영역.*간접비/.test(compact))return {changeType:'기준/요건 변경',riskLevel:'높음',riskScore:78,summary:'연구영역 평가항목을 필수업적(논문등)과 필수업적(간접비)로 세분화하고 배점 반영 구조를 바꾸는 개정입니다.',impact:'교원업적평가 산정 방식, 간접비 실적 관리, 교원 안내자료와 시행세칙 산식 정비가 필요합니다. 평가 대상 기간과 2027년 적용 기준도 함께 확인해야 합니다.',questions:['필수업적(논문등) 90%와 필수업적(간접비) 10% 반영 산식이 시행세칙과 일치하는가?','간접비 실적 산정 기준과 데이터 출처가 교원별로 검증 가능한가?','2027년 교원업적평가 적용 시점과 기존 평가자료 경과조치가 명확한가?','계열 구분 기준이 교원 인사 규정 별표와 충돌하지 않는가?'],opinionDraft:'연구영역 평가를 논문등 실적과 간접비 실적으로 분리하려는 취지는 인정됩니다. 다만 산식·계열 구분·적용 시점이 교원업적평가 시행세칙 및 교원 인사 규정과 일치하는지 확인하고, 교원 안내 및 실적 검증 절차를 함께 정비하는 조건으로 검토하는 것이 타당합니다.',riskDrivers:['교원 평가점수 산정 방식 변경','간접비 실적이라는 신규 평가축 반영','시행세칙·교원 인사 규정 별표와의 정합성 확인 필요']};
  if(/제4조의4|예술계열교원의연구업적인정|초과강의/.test(compact))return {changeType:'기준/요건 변경',riskLevel:'보통',riskScore:62,summary:'예술계열 교원의 초과강의 관련 연구업적 인정 문구를 필수요건 인정 구조에 맞게 정비하는 개정입니다.',impact:'예술계열 교원의 연구업적 인정 범위와 초과강의료 미지급 기준 안내가 필요합니다. 기존 제18조 및 연구업적 산정기준과 문구가 맞는지 확인해야 합니다.',questions:['초과강의 1시간당 인정 비율과 필수요건 인정 방식이 연구업적 산정기준과 일치하는가?','초과강의료 미지급 조항과 교원 보수·강의 관련 기준이 충돌하지 않는가?','예술계열 적용 대상이 제18조 제2호와 동일하게 유지되는가?'],opinionDraft:'문구 정비 성격이 강하지만 예술계열 교원의 연구업적 인정 및 초과강의료 미지급과 연결되므로, 연구업적 산정기준과 보수 관련 기준을 함께 확인한 뒤 확정하는 것이 적절합니다.',riskDrivers:['예술계열 연구업적 인정 기준 변경','초과강의료 미지급 문구와의 연결','연구업적 산정기준 원문 확인 필요']};
  if(/제3조\(구성\)|외부전문가.*2명이상|사립학교법|상위법령개정반영/.test(compact))return {changeType:'상위법령 반영 의심',riskLevel:'높음',riskScore:82,summary:'기금운용심의회 외부전문가 요건을 1명 이상에서 2명 이상으로 확대하여 상위법령 개정사항을 반영하는 개정입니다.',impact:'위원회 구성 요건이 강화되므로 위촉 인원, 임기, 현 위원 구성의 적법성, 시행일 이후 회의 성립 요건을 점검해야 합니다.',questions:['사립학교법 제32조의3 최신 조문에서 외부전문가 2명 이상 요건이 citation으로 확인되는가?','현재 기금운용심의회 위원 구성에서 외부전문가 2명 이상을 충족하는가?','시행일 전후 개최되는 회의에 경과조치가 필요한가?'],opinionDraft:'상위법령 개정에 따른 후속 정비로 보이며 개정 필요성이 높습니다. 다만 실제 사립학교법 최신 조문 citation을 확인하고, 현재 위원 구성 및 시행일 이후 회의 운영에 공백이 없는지 점검한 뒤 확정하는 것이 적절합니다.',riskDrivers:['상위법령 개정사항 반영','위원회 외부전문가 구성 요건 강화','시행일 이후 위원 구성 충족 여부 확인 필요']};
  if(/제11조\(단장\)|2년미만의기간|특별한사유|단서조항신설/.test(compact))return {changeType:'권한/책임 변경',riskLevel:'보통',riskScore:58,summary:'연구산학협력단장 임기를 원칙 2년으로 유지하되 특별한 사유가 있으면 2년 미만으로 정할 수 있는 예외 단서를 신설하는 개정입니다.',impact:'보직 공백 방지에는 도움이 되지만, 예외 임기 결정권자와 특별한 사유의 판단 기준이 불명확하면 인사 운영상 논란이 생길 수 있습니다.',questions:['2년 미만 임기를 정할 수 있는 결정권자와 절차가 정관 또는 위임규정에 명확한가?','특별한 사유의 예시나 판단 기준을 별도 지침으로 둘 필요가 있는가?','현재 단장 임기 만료·후임 임명 일정과 연결된 경과조치가 필요한가?'],opinionDraft:'행정 공백 방지를 위한 예외 단서 신설 취지는 타당합니다. 다만 특별한 사유의 판단 주체와 절차가 불명확하면 자의적 운영 우려가 있으므로, 위임권한과 적용 기준을 확인한 뒤 확정하는 것이 좋습니다.',riskDrivers:['보직 임기 예외 단서 신설','특별한 사유 판단 기준 필요','인사 권한·위임 절차 확인 필요']};
  if(/부칙|시행일|경과조치/.test(compact))return {changeType:'절차 변경',riskLevel:'보통',riskScore:55,summary:'개정 규정의 시행일과 적용 시점 또는 경과조치를 정하는 부칙입니다.',impact:'시행일과 실제 적용 대상 기간이 어긋나면 기존 사건·평가·위원회 구성에 혼선이 생길 수 있으므로 본문 개정내용과 함께 확인해야 합니다.',questions:['본문 개정사항별 시행일이 하나로 충분한가, 별도 적용일이 필요한가?','기존 재직자·기존 평가대상·현재 위원에게 적용되는 경과조치가 필요한가?','이전 부칙이나 관련 규정의 시행일과 충돌하지 않는가?'],opinionDraft:'부칙은 개정안의 실제 적용 범위를 결정하므로 본문 변경사항과 함께 검토해야 합니다. 시행일, 적용 대상, 경과조치가 명확하면 실무 혼선을 줄일 수 있습니다.',riskDrivers:['시행일·적용시점 확인 필요','경과조치 필요성 검토','본문 개정사항과 부칙 정합성 확인']};
  return undefined;
}

function inferReason(row:ParsedComparisonRow){if(!row.oldText&&row.newText)return '신설';if(row.oldText&&!row.newText)return '삭제';return '공개 신구조문 대비표 기준 변경사항';}
function summarize(t:ChangeType){if(t==='신설')return '새로운 의무 또는 절차가 추가되었습니다.';if(t==='삭제')return '기존 근거 조항이 삭제되었습니다.';if(t==='변경')return '성신 현행 조문과 업로드 개정안 사이에 본문 변경이 있습니다.';if(t==='절차 변경')return '임의 절차가 의무 절차로 강화되었을 가능성이 있습니다.';if(t==='권한/책임 변경')return '위원회 또는 담당 주체의 구성·책임 범위가 변경되었습니다.';return '표현 또는 운영 기준이 일부 정비되었습니다.'}
function impact(t:ChangeType){return t==='절차 변경'||t==='신설'?'실무 처리기간, 담당부서 업무량, 위원회 상정 필요성이 증가할 수 있습니다.':t==='권한/책임 변경'?'담당 주체와 의사결정 권한의 정합성 확인이 필요합니다.':'실무 영향은 제한적이나 다른 조항과 용어 일치 여부 확인이 필요합니다.'}
function questions(t:ChangeType){return ['상위 규정 또는 법령 위임 근거가 명확한가?','시행일 이전 경과조치가 필요한가?',t==='신설'||t==='절차 변경'?'담당부서가 실제 이행 가능한 절차인가?':'기존 조항과 용어가 일관되는가?'];}
function opinion(t:ChangeType,row:{reason:string}){return `본 개정안은 ${row.reason} 측면에서 필요성이 인정됩니다. 다만 ${t==='신설'||t==='절차 변경'?'의무 부과 및 절차 강화에 따른 상위 규정 근거와 실무 이행 가능성':'기존 규정 체계와의 정합성'}을 추가 확인한 후 확정하는 것이 타당합니다.`}
